import argparse
from pathlib import Path
from subprocess import run


VIDEO_SUFFIX = "_injected.hevc"
CHAPTERS_SUFFIX = ".chapters.txt"


def main():
    parser = argparse.ArgumentParser(description="Merge DV hybrid video streams generated by dv_hybrid into .mkv files")
    parser.add_argument('outpath', type=str, help="Output path for merged files.")
    args = parser.parse_args()

    out = Path(args.outpath).resolve()

    files = sorted(Path('.').glob("*.mkv"))

    for i, file in enumerate(files):
        print(f"File {i + 1} of {len(files)}")
        print(f"Merging {file}")

        video_stream = Path(f"{file.stem}{VIDEO_SUFFIX}")
        sub_file = sorted(Path('.').glob(f"{file.stem}*.srt"))[0]
        chapters_file = Path(f"{file.stem}{CHAPTERS_SUFFIX}")

        run(["mkvmerge", "--output", out / file.name, "--no-video", "--no-subtitles", "(", file, ")",
            "(", video_stream, ")", "--language", "0:en", "--default-track-flag", "0:no", "(", sub_file, ")",
            "--chapter-language", "en", "--chapter-charset", "UTF-8", "--chapters", chapters_file, "--track-order", "1:0,0:1,2:0"])


if __name__ == "__main__":
    main()
